plugins {
    id 'com.android.application'
}

def releaseKeystorePath = System.getenv('YAGSATIS_KEYSTORE_PATH')
def releaseStorePassword = System.getenv('YAGSATIS_KEYSTORE_PASSWORD')
def releaseKeyAlias = System.getenv('YAGSATIS_KEY_ALIAS')
def releaseKeyPassword = System.getenv('YAGSATIS_KEY_PASSWORD')

android {
    namespace 'com.yagsatis.mobile'
    compileSdk 35

    defaultConfig {
        applicationId 'com.yagsatis.mobile'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '1.1.1'
    }

    signingConfigs {
        release {
            if (releaseKeystorePath && releaseStorePassword && releaseKeyAlias && releaseKeyPassword) {
                storeFile file(releaseKeystorePath)
                storePassword releaseStorePassword
                keyAlias releaseKeyAlias
                keyPassword releaseKeyPassword
            }
        }
    }

    buildTypes {
        release {
            if (releaseKeystorePath && releaseStorePassword && releaseKeyAlias && releaseKeyPassword) {
                signingConfig signingConfigs.release
            }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
